config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/registration', to: 'devise/registrations#new'
    post '/registration', to: 'devise/registrations#create'
  end
  get '/map', to: 'pages#map'
  post '/map', to: 'pages#map'
  post '/words/find_region', to: 'words#find_region'
  post '/words/find_district', to: 'words#find_district'
  post '/words/find_city', to: 'words#find_city'
  post '/pages/words_search', to: 'pages#words_search'
  root to: 'pages#index'
  get '/news', to: 'posts#news'
  get '/articles', to: 'posts#articles'
  resources :words do
    member do
      patch :approve
    end
  end
  resources :posts do
    resources :comments
  end
  resources :letters
  get '/contacts', to: 'letters#index'
  get '/map', to: 'pages#map'
  get '/about-us', to: 'pages#about_us'
  get '/profile', to: 'users#profile'
  get '/users-list', to: 'users#index'
  resources :users
  get '/search', to: 'pages#search'
  post '/search', to: 'pages#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :post

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/city.rb
class City < ApplicationRecord
  has_many :words
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/letter.rb
class Letter < ApplicationRecord
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :attachments
  has_many :comments
  belongs_to :category
  belongs_to :user
  has_attached_file :mainphoto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :mainphoto, content_type: /\Aimage\/.*\z/
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :role_category
end

app/models/role_category.rb
class RoleCategory < ApplicationRecord
  has_many :roles
end

app/models/user.rb
class User < ApplicationRecord
  has_one  :role
  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, default_url: "/images/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :city
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  def index
  end

  def create
    @letter = Letter.new(letter_params)
    if @letter.save
      redirect_to root_path
    else
      render '/index'
    end
  end

  private

  def letter_params
    params.require(:letter).permit(:name, :email, :phone, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @news = Post.where(category_id: 1).last(3)
    @articles = Post.where(category_id: 2).last(3)
  end

  def map
  end

  def words_search
    @words = Word.where(official_word: params.keys[0], confirmed: true)

   respond_to do |format|
     format.json { render json: @words }
   end
  end

  def about_us
  end

  def search
    if !params[:search].nil?
      @users = User.where(email: params[:search][:search_text]) + User.where(name: params[:search][:search_text]) + User.where(surname: params[:search][:search_text])
      @posts = Post.where(article: params[:search][:search_text])
      @words = Word.where(official_word: params[:search][:search_text]) + Word.where(dialect_word: params[:search][:search_text])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:destroy, :edit, :update, :show]
  before_action :authenticate_user!, only: [:new, :edit]

  def news
    @news = Post.where(category_id: 1)
  end

  def articles
    @articles = Post.where(category_id: 2)
  end

  def new
  end

  def create
    params[:post][:user_id] = current_user.id
    params[:post][:category_id] = params[:category_id]
    @post = Post.new(post_params)
    pp @post
    if @post.save
      if params[:images]
        params[:images].each do |photo|
          @files = @post.attachments.create(photo: photo)
        end
      end
      redirect_to @post
    else
      render '/posts/new'
    end
  end

  def edit
  end

  def update
    params[:post][:category_id] = params[:category_id]
    @post.update(post_params)
    redirect_to root_path
  end

  def show
    @photos = @post.attachments
    @comments = @post.comments
  end

  def destroy
    @post.destroy
    redirect_to '/news'
  end

  private

  def attachment_params
    params.require(:attachments).permit(:post_id, :photo)
  end

  def post_params
    params.require(:post).permit(:article, :body, :category_id, :mainphoto, :user_id)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def profile
    @posts = current_user.posts
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/letters/index.html.erb
<h2 align="center">Контакти</h2>

<div class="row">
   <div class="col-sm-6">
       <table align="center">
           <tr>
                <td><i class="	glyphicon glyphicon-earphone"></i> Наші телефони:</td>
            </tr>
            <tr>
              <td>+380 (66) 51 63 606 </td>
            </tr>
            <tr>
              <td>+380 (68) 90 56 527 </td>
            </tr>
        </table>
   </div>
   <div class="col-sm-6">
       <table align="center">
           <tr>
                <td><i class="glyphicon glyphicon-envelope"></i> Пошта:</td>
                <td>mail@uzhnu.edu.ua</td>
            </tr>
            <tr>
              <td><i class="glyphicon glyphicon-send"></i> Телеграм:</td>
              <td>@dulgeoion</td>
            </tr>
            <tr>
              <td><i class="	glyphicon glyphicon-phone-alt"></i> Skype:</td>
              <td>duri-d265</td>
            </tr>
        </table>
   </div>
</div>
<div class="feedback">
     <h3 align="center">Напишіть нам листа!</h3>
  <%= form_for :letter, class: "form-group", url: letters_path do |f| %>
  <label for="usr">Ім'я <span class="red-star">*</span>:</label>
    <%= f.text_field :name, class: "form-control "%>
    <label for="usr">Пошта<span class="red-star">*</span>:</label>
    <%= f.text_field :email, class: "form-control " %>
    <label for="usr">Телефон<span class="red-star">*</span>:</label>
    <%= f.text_field :phone, class: "form-control " %>
    <label for="usr">Текст повідомлення<span class="red-star">*</span>  :</label>
    <%= f.text_area :body, class: "form-control " %>
    <%= f.submit "Відправити!", class: "btn btn-default" %>
  <% end %>

 </div>