config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/registration', to: 'devise/registrations#new'
    post '/registration', to: 'devise/registrations#create'
  end
  get '/map', to: 'pages#map'
  post '/map', to: 'pages#map'
  post '/words/find_region', to: 'words#find_region'
  post '/words/find_district', to: 'words#find_district'
  post '/words/find_city', to: 'words#find_city'
  post '/pages/words_search', to: 'pages#words_search'
  root to: 'pages#index'
  get '/news', to: 'posts#news'
  get '/articles', to: 'posts#articles'
  resources :words do
    member do
      patch :approve
    end
  end
  resources :posts do
    resources :comments
  end
  resources :letters
  get '/contacts', to: 'letters#index'
  get '/map', to: 'pages#map'
  get '/about-us', to: 'pages#about_us'
  get '/profile', to: 'users#profile'
  get '/users-list', to: 'users#index'
  resources :users
  get '/search', to: 'pages#search'
  post '/search', to: 'pages#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :post

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/city.rb
class City < ApplicationRecord
  has_many :words
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/letter.rb
class Letter < ApplicationRecord
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :attachments
  has_many :comments
  belongs_to :category
  belongs_to :user
  has_attached_file :mainphoto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :mainphoto, content_type: /\Aimage\/.*\z/
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :role_category
end

app/models/role_category.rb
class RoleCategory < ApplicationRecord
  has_many :roles
end

app/models/user.rb
class User < ApplicationRecord
  has_one  :role
  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, default_url: "/images/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :city
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @news = Post.where(category_id: 1).last(3)
    @articles = Post.where(category_id: 2).last(3)
  end

  def map
  end

  def words_search
    @words = Word.where(official_word: params.keys[0], confirmed: true)

   respond_to do |format|
     format.json { render json: @words }
   end
  end

  def about_us
  end

  def search
    if !params[:search].nil?
      @users = User.where(email: params[:search][:search_text]) + User.where(name: params[:search][:search_text]) + User.where(surname: params[:search][:search_text])
      @posts = Post.where(article: params[:search][:search_text])
      @words = Word.where(official_word: params[:search][:search_text]) + Word.where(dialect_word: params[:search][:search_text])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:destroy, :edit, :update, :show]
  before_action :authenticate_user!, only: [:new, :edit]

  def news
    @news = Post.where(category_id: 1)
  end

  def articles
    @articles = Post.where(category_id: 2)
  end

  def new
  end

  def create
    params[:post][:user_id] = current_user.id
    params[:post][:category_id] = params[:category_id]
    @post = Post.new(post_params)
    pp @post
    if @post.save
      if params[:images]
        params[:images].each do |photo|
          @files = @post.attachments.create(photo: photo)
        end
      end
      redirect_to @post
    else
      render '/posts/new'
    end
  end

  def edit
  end

  def update
    params[:post][:category_id] = params[:category_id]
    @post.update(post_params)
    redirect_to root_path
  end

  def show
    @photos = @post.attachments
    @comments = @post.comments
  end

  def destroy
    @post.destroy
    redirect_to '/news'
  end

  private

  def attachment_params
    params.require(:attachments).permit(:post_id, :photo)
  end

  def post_params
    params.require(:post).permit(:article, :body, :category_id, :mainphoto, :user_id)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def profile
    @posts = current_user.posts
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
before_action :find_word, only: [:destroy, :edit, :update, :approve]
skip_before_action :verify_authenticity_token

  def index
    @words = Word.where(confirmed: true)
  end

  def new
  end

  def create
    city = City.find_by(city: params.values[0])
    @word = Word.new
    if user_signed_in?
      @word.user_id = current_user.id
    else
      @word.user_id = 1
    end
    @word.city_id = city.id
    @word.official_word = params.values[1]
    @word.dialect_word = params.values[2]
    @word.transcription = params.values[3]
    @word.save
    redirect_to '/map'
  end

  def find_region
    @districts = City.where(region: params.keys[0])
    @districts = @districts.map { |e| e.district  }

    respond_to do |format|
      format.json { render json: @districts.uniq }
    end
  end

  def find_district
    @cities = City.where(district: params.keys[0])
    @cities = @cities.map { |e| e.city  }

    respond_to do |format|
      format.json { render json: @cities.uniq }
    end
  end

  def edit
    pp @word
  end

  def update
    @city = City.where(city: params.values[0])
    @word.city_id = @city.id
    @word.official_word = params.values[1]
    @word.dialect_word = params.values[2]
    @word.update
    redirect_to '/words'
  end

  def destroy
    @word.destroy
    redirect_to '/words'
  end

  def approve
    @word.confirmed = true
    @word.save
    redirect_to words_path
  end

  private
    def word_params
      params.require(:word).permit(:official_word, :dialect_word, :city_id, :user_id)
    end

    def find_word
      @word = Word.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/posts/_form.html.erb
<label>Назва статті:</label>
<%= f.text_field :article, class: 'form-control' %>
<label>Текст статті:</label>
<%= f.text_area :body, class: "tinymce", rows: 20, cols: 120 %><br/>
<label>Завантажте мініатюру:</label>
<%= f.file_field :mainphoto, class: "form-control-file" %>
<label>Категорія статті:</label>
<%= select_tag "category_id", options_from_collection_for_select(Category.all, :id, :name) , class: 'form-control'%>
<%= f.label "Завантажити файли:" %>
<%= file_field_tag "images[]", type: :file, multiple: true, class: "form-control-file"%>
<%= f.submit "Опублікувати статтю", class: "btn btn-default" %>

app/views/posts/articles.html.erb
<h2 align="center">Cтатті</h2>
<%= link_to 'Додати статтю', new_post_path , class: "btn btn-default" if user_signed_in?%><br/>
<div class="articles">
<% @articles.each do |a| %>
 <div class="article col-sm-12 col-xs-12">
    <div class="img">
      <%= image_tag a.mainphoto.url , class: 'img-responsive' %>
    </div>
    <div class="title">
      <h5><%= a.category.name %></h5>
      <hr class="blog-hr">
      <h3 class=""><%= link_to a.article, post_path(a.id) %></h3>
      <%= truncate sanitize(a.body), length: 100, escape: false %>
    <% if user_signed_in? && a.user_id.to_i.equal?(current_user.id) %>
      <div class="article-control-links">
        <hr align="right" width="25%">
        <%= link_to 'Редагувати', edit_post_path(a.id) %>
        <%= link_to 'Видалити', post_path(a.id), method: :delete %>
       </div>
    <% end %>
  </div>

  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<%= form_for :post, url: post_path, method: :patch do |f| %>
  <%= render 'form', f:f %>
  <%= tinymce %>
<% end %>

app/views/posts/new.html.erb
<%= form_for :post, url: posts_path, html: { multipart: true } do |f| %>
  <%= render 'form', f:f %>
  <%= tinymce %>
<% end %>

app/views/posts/news.html.erb
<h2 align="center">Новини</h2>
<%= link_to 'Додати новину', new_post_path , class: "btn btn-default" if user_signed_in?%><br/>
<div class="articles">
<% @news.each do |n| %>
<div class="article col-sm-12 col-xs-12">
   <div class="img">
     <%= image_tag n.mainphoto.url , class: 'img-responsive' %>
   </div>
   <div class="title">
     <h5><%= n.category.name %></h5>
     <hr class="blog-hr">
     <h3 class=""><%= link_to n.article, post_path(n.id) %></h3>
     <%= truncate sanitize(n.body), length: 100, escape: false %>
   <% if user_signed_in? && n.user_id.to_i.equal?(current_user.id) %>
     <div class="article-control-links">
       <hr align="right" width="25%">
       <%= link_to 'Редагувати', edit_post_path(n.id) %>
       <%= link_to 'Видалити', post_path(n.id), method: :delete %>
      </div>
   <% end %>
 </div>

 </div>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="article-show">
   <div class="img">
   <%= image_tag @post.mainphoto.url, class: "img-responsive" %>
   </div>
   <div class="post">
     <h5  class="category"><%= @post.category.name %></h5>
     <hr class="blog-hr">
       <h2 class="title"><%= @post.article %></h2>
       <span class="post-body"> <%= sanitize(@post.body) %> </span>

       <% if user_signed_in? &&  @post.user_id.to_i.equal?(current_user.id) %>
         <div class="article-control-links">
         <hr align="right" width="25%">
           <%= link_to 'Редагувати', edit_post_path(@post.id) %>
           <%= link_to 'Видалити', post_path(@post.id), method: :delete %>
          </div>
       <% end %>
</div>
<%# if @comments.present? %>
  <%# @comments.each do |comment| %>
    <%#= comment.user.name %>
    <%#= comment.text %>
  <%# end %>
<%# end %>
</div>
</div>
<br/>

<div class="contariner">
<br/>
<div class="container">
  <%#= form_for :comment, url: post_comments_path(@post.id) do |f| %>
    <%#= f.label :text %>
    <%#= f.text_area :text %>
    <%#= f.submit 'Save comment' %>
  <%# end %>
</div>

app/views/words/_form.html.erb
<div class='dropdown-selectors'>
  <%#= form_for :word, remote: true, formt: :json do |f| %>
  <%# end %>
<select id="region" onchange="selectRegion(this.value)">
      <option>Виберіть область</option>
      <option value="Одеська">Одеська область</option>
      <option value="Дніпропетровська">Дніпропетровська область</option>
      <option value="Чернігівська">Чернігівська область</option>
      <option value="Харківська">Харківська область</option>
      <option value="Житомирська">Житомирська область</option>
      <option value="Полтавська">Полтавська область</option>
      <option value="Херсонська">Херсонська область</option>
      <option value="Київська">Київська область</option>
      <option value="Запорізька">Запорізька область</option>
      <option value="Луганська">Луганська область</option>
      <option value="Донецька">Донецька область</option>
      <option value="Вінницька">Вінницька область</option>
      <option value="Крим">Автономна Республіка Крим</option>
      <option value="Миколаївська">Миколаївська область</option>
      <option value="Кіровоградська">Кіровоградська область</option>
      <option value="Сумська">Сумська область</option>
      <option value="Львівська">Львівська область</option>
      <option value="Черкаська">Черкаська область</option>
      <option value="Хмельницька">Хмельницька область</option>
      <option value="Волинська">Волинська область</option>
      <option value="Рівненська">Рівненська область</option>
      <option value="Івано-Франківська">Івано-Франківська область</option>
      <option value="Тернопільська">Тернопільська область</option>
      <option value="Закарпатська">Закарпатська область</option>
      <option value="Чернівецька">Чернівецька область</option>
    </select>


    <select id="district" onchange="selectDistrict(this.value)">
      <option >Виберіть район </option>
    </select>


    <select id="city">
      <option>Виберіть населенний пункт</option>
    </select>


</div>

<br/>
<br/>

<form name="test" method="post" onsubmit="addWord(off.value,dial.value); return false;" >
  <input type="text" name="off" class="ntSaveForms" placeholder="Слово" size="40">
  <input type="text" name="dial" class="ntSaveForms" placeholder="Діалект" size="40">
  <input type="text" name="transcription" id="transcription" class="ntSaveForms" placeholder="[ Транскрипція до діалектизму ]" size="40">
  <button type="button" id="open-transcription" value="Допоміжні символи">Допоміжні символи</button>
  <button type="submit" value="Отправить">Додати</a></button>
  <%= render "words/transcription_panel" %>
</form>

app/views/words/_transcription_panel.html.erb
<div id="transcription-panel" draggable="true">
<div class="close">X</div>
<table id="symbols">
  <tr>
    <th colspan="33">Панель транскрипцій</th>
  </tr>
  <tr>
    <td>[</td>
    <td>]</td>
    <td>'</td>
    <td> ́</td>
    <td>˄</td>
    <td>:</td>
    <td>ў</td>
    <td>ĭ</td>
    <td>еᴻ</td>
    <td>иᵉ</td>
    <td>оʸ</td>
    <td>д͡ж</td>
    <td>д͡з</td>
  </tr>
</table>
<div id="additional-symbols">
  <table id='alphabet'>
    <tr>
      <th colspan="33">Алфавіт</th>
    </tr>
    <tr>
      <td>а</td>
      <td>б</td>
      <td>в</td>
      <td>г</td>
      <td>ґ</td>
      <td>д</td>
      <td>е</td>
      <td>є</td>
      <td>ж</td>
      <td>з</td>
      <td>и</td>
      <td>і</td>
      <td>й</td>
      <td>к</td>
      <td>л</td>
      <td>м</td>
      <td>н</td>
      <td>о</td>
      <td>п</td>
      <td>р</td>
      <td>с</td>
      <td>т</td>
      <td>у</td>
      <td>ф</td>
      <td>х</td>
      <td>ц</td>
      <td>ч</td>
      <td>ш</td>
    </tr>
  </table>

  <table id='emphasis' style='display:none;'>
    <tr>
      <th colspan="10">Наголоси</th>
    </tr>
    <tr>
      <td>á</td>
      <td>é</td>
      <td>í</td>
      <td>ó</td>
      <td>ý</td>
      <td>и́</td>
    </tr>
  </table>

  <table id='roof' style='display:none;'>
    <tr>
      <th colspan="10">Дашки</th>
    </tr>
    <tr>
      <td>â</td>
      <td>ê</td>
      <td>î</td>
      <td>ô</td>
      <td>ŷ</td>
      <td></td>
    </tr>
  </table>
</div>
<p><em>Панель можна перетягувати по робочій області, просто зажміть мишою :)</em></p>
</div>

app/views/words/edit.html.erb
<%= @word.id %>
<div style="float:left">
  <select id="region" onchange="selectRegion(this.value)">
    <option>Виберіть область</option>
    <option value="Одеська">Одеська область</option>
    <option value="Дніпропетровська">Дніпропетровська область</option>
    <option value="Чернігівська">Чернігівська область</option>
    <option value="Харківська">Харківська область</option>
    <option value="Житомирська">Житомирська область</option>
    <option value="Полтавська">Полтавська область</option>
    <option value="Херсонська">Херсонська область</option>
    <option value="Київська">Київська область</option>
    <option value="Запорізька">Запорізька область</option>
    <option value="Луганська">Луганська область</option>
    <option value="Донецька">Донецька область</option>
    <option value="Вінницька">Вінницька область</option>
    <option value="Крим">Автономна Республіка Крим</option>
    <option value="Миколаївська">Миколаївська область</option>
    <option value="Кіровоградська">Кіровоградська область</option>
    <option value="Сумська">Сумська область</option>
    <option value="Львівська">Львівська область</option>
    <option value="Черкаська">Черкаська область</option>
    <option value="Хмельницька">Хмельницька область</option>
    <option value="Волинська">Волинська область</option>
    <option value="Рівненська">Рівненська область</option>
    <option value="Івано-Франківська">Івано-Франківська область</option>
    <option value="Тернопільська">Тернопільська область</option>
    <option value="Закарпатська">Закарпатська область</option>
    <option value="Чернівецька">Чернівецька область</option>
  </select>
</div>

<div style="float:left;">
  <select id="district" onchange="selectDistrict(this.value)">
    <option >Виберіть район </option>
  </select>
</div>

<div style="float:left;">
  <select id="city">
    <option>Виберіть населенний пункт</option>
  </select>
</div>

<br/>
<br/>

<form name="test"  onsubmit="editWord(off.value,dial.value); return false;" >
  <input type="text" name="off" class="ntSaveForms" placeholder="Слово" size="40">
  <input type="text" name="dial" class="ntSaveForms" placeholder="Діалект" size="40">
  <button type="submit" value="Отправить">Додати</a></button>
</form>

<script type="text/javascript">
  console.log(query.regparams)
  editWord = (off, dial) => {
    data = document.getElementById('city').value
    url = '/words/' + <%= @word.id %>
    alert(url);
    $.ajax({
      type: 'PATCH',
      url: url,
      contentType: 'application/json',
      data: JSON.stringify({ data: data,
              off: off,
              dial: dial }),
      success: function(data, off, dial) {
        console.log('success')
      },
      error: function(data) {
        console.log('error')
      }
    });
  }
</script>

app/views/words/index.html.erb
<% @words.each do |word| %>
  <%= word.official_word %>
  <%= word.dialect_word %>
  <%= word.city.city %>
  <%= link_to 'Edit', edit_word_path(word) %>
  <%= link_to 'Delete', word_path(word), method: :delete %>
  <%= link_to 'Approve Word', approve_word_path(word), method: :patch unless word.confirmed %>
  <br/>
<% end %>

app/views/words/new.html.erb
<%= render 'words/form' %>