config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/registration', to: 'devise/registrations#new'
    post '/registration', to: 'devise/registrations#create'
  end
  get '/map', to: 'pages#map'
  post '/map', to: 'pages#map'
  post '/words/find_region', to: 'words#find_region'
  post '/words/find_district', to: 'words#find_district'
  post '/words/find_city', to: 'words#find_city'
  post '/pages/words_search', to: 'pages#words_search'
  root to: 'pages#index'
  get '/news', to: 'posts#news'
  get '/articles', to: 'posts#articles'
  resources :words do
    member do
      patch :approve
    end
  end
  resources :posts do
    resources :comments
  end
  resources :letters
  get '/contacts', to: 'letters#index'
  get '/map', to: 'pages#map'
  get '/about-us', to: 'pages#about_us'
  get '/profile', to: 'users#profile'
  get '/users-list', to: 'users#index'
  resources :users
  get '/search', to: 'pages#search'
  post '/search', to: 'pages#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :post

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/city.rb
class City < ApplicationRecord
  has_many :words
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/letter.rb
class Letter < ApplicationRecord
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :attachments
  has_many :comments
  belongs_to :category
  belongs_to :user
  has_attached_file :mainphoto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :mainphoto, content_type: /\Aimage\/.*\z/
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :role_category
end

app/models/role_category.rb
class RoleCategory < ApplicationRecord
  has_many :roles
end

app/models/user.rb
class User < ApplicationRecord
  has_one  :role
  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, default_url: "/images/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :city
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @news = Post.where(category_id: 1).last(3)
    @articles = Post.where(category_id: 2).last(3)
  end

  def map
  end

  def words_search
    @words = Word.where(official_word: params.keys[0], confirmed: true)

   respond_to do |format|
     format.json { render json: @words }
   end
  end

  def about_us
  end

  def search
    if !params[:search].nil?
      @users = User.where(email: params[:search][:search_text]) + User.where(name: params[:search][:search_text]) + User.where(surname: params[:search][:search_text])
      @posts = Post.where(article: params[:search][:search_text])
      @words = Word.where(official_word: params[:search][:search_text]) + Word.where(dialect_word: params[:search][:search_text])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/_footer.html.erb
<footer align="center">
		<hr />
		<h6>2017-2018 © Ділаекти України</h6>
		<h6>Всі права захищені правовласниками</h6>
	</footer>

app/views/layouts/_header.html.erb
<header>

		<h1 class="logo">Діалекти України</h1>
		<hr class="underlogo" />
		<h3 class="subtitle">ІНТЕРАКТИВНА КАРТА ДІАЛЕКТІВ УКРАЇНИ</h3>

		<%= render "layouts/navbar" %>

</header>

app/views/layouts/_navbar.html.erb
<ul class="nav nav-pills nav-justified main-nav">
      <li class="nav-item">
        <a class="nav-link active" href="/">Головна</a>
      </li>
      <li class="nav-item">
        <a class="nav-link mylink" href="/about-us">Про нас</a>
      </li>
      <li class="nav-item">
        <a class="nav-link mylink" href="/map">Карта</a>
      </li>
        <li class="nav-item myitem">
          <a class="nav-link" href="/news">Новини</a>
        </li>
      <li class="nav-item">
        <a class="nav-link" href="/articles">Статті</a>
      </li>
        <li class="nav-item">
          <a class="nav-link" href="/contacts">Контакти</a>
        </li>
        <% if !user_signed_in? %>
      <li class="nav-item">
        <a class="nav-link" href="/login">Вхід</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/registration">Реєстрація</a>
      </li>
      <% else %>
      <li class="nav-item">
          <a class="nav-link" href="/profile">Профіль</a>
      </li>
      <li class="nav-item">
        <%= link_to "Вийти", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% end %>
  </ul>

app/views/layouts/_search.html.erb
<%= form_for :search, url: search_path do |f| %>
  <%= f.label :search_text %>
  <%= f.text_field :search_text %>
  <%= f.submit "Search" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dialect</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= render "layouts/header" %>
      <%#= render 'layouts/search' %>
      <%= yield %>
      <%= render "layouts/footer" %>

  </div>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1 align="center">Про нас</h1>
        <section class="about-us-page">
           <div class="about-project">
                <div class="about-project-header">
                        <img src="/images/about-us.jpg" alt="">
                        <h2>Про проект</h2>
                </div>
                <div class="about-project-body">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea obcaecati praesentium, eos soluta accusamus magni corrupti! Illum dolorem et earum ducimus laudantium iste possimus nam quibusdam, dignissimos a perferendis provident!
                </div>
           </div>
           <div class="goals-and-audience">
                <div class="goals-and-audience-header">
                        <img src="/images/audience.jpg" alt="">

                        <h2>Цілі та аудиторія</h2>
                </div>
                <div class="goals-and-audience-body">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea obcaecati praesentium, eos soluta accusamus magni corrupti! Illum dolorem et earum ducimus laudantium iste possimus nam quibusdam, dignissimos a perferendis provident!
                </div>
           </div>
           <div class="team">
                <div class="team-header">
                        <img src="/images/team.jpg" alt="">
                        <h2>Команда</h2>
                </div>
                <div class="team-body">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea obcaecati praesentium, eos soluta accusamus magni corrupti! Illum dolorem et earum ducimus laudantium iste possimus nam quibusdam, dignissimos a perferendis provident!
                </div>
           </div>
           <div class="contact-us">
                   <img src="/images/glenn-carstens-peters-112923.jpg" alt="">
                   <h2>Виникли питання?</h2>
                   <button class="btn btn-default btn-contact" href="/contacts" formtarget="_blank" onclick="parent.location='/contacts'">Надішліть нам листа!</button>
           </div>
        </section>

app/views/pages/index.html.erb
<section>


  <div class="row about-us-homepage">
    <div class="col-sm-6 col-xs-12 about-us-img">
    </div>
    <div class="col-sm-6 col-xs-12 about-us-content">
      <h4>Про нас</h4>
      <hr class="blog-hr">
      <p>	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis veritatis, fuga at hic veniam, dignissimos optio nemo possimus rem expedita ratione rerum? Explicabo, iusto beatae veritatis cupiditate modi labore eligendi.</p>
      <p>	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis veritatis, fuga at hic veniam, dignissimos optio nemo possimus rem expedita ratione rerum? Explicabo, iusto beatae veritatis cupiditate modi labore eligendi.</p>
    </div>
  </div>
  <h2 align="center">Останні новини</h2>

  <div class="row article-row">
    <% @news.each do |n| %>
      <div class="article col-sm-4 col-xs-12">
        <div class="img">
          <%= image_tag n.mainphoto.url, class: 'thumb img-responsive' %>
        </div>
        <div class="title">
          <h5><%= n.category.name %></h5>
          <hr class="blog-hr">
          <h3 class=""><%= link_to n.article, post_path(n.id) %></h3>
        </div>
      </div>
    <% end %>
  </div>

  <h2 align="center">Останні записи</h2>

  <div class="row article-row">
    <% @articles.each do |a| %>
    <div class="article col-sm-4 col-xs-12">
      <div class="img">
        <%= image_tag a.mainphoto.url, class: 'thumb img-responsive' %>
      </div>
      <div class="title">
        <h5><%= a.category.name %></h5>
        <hr class="blog-hr">
        <h3 class=""><%= link_to a.article, post_path(a.id) %></h3>
      </div>
    </div>
    <% end %>
  </div>


</section>

app/views/pages/map.html.erb
  <div id="Search", class="center row">
    <form name="test" method="post"  onsubmit="selectWords(off.value); return false;" >
      <input type="text" name="off" class="ntSaveForms" placeholder="Слово" size="40">
      <button type="submit" value="Отправить">Знайти</a></button>
    </form>
  </div>

  <div id="add-word-section" align='center'>
    <%= render 'words/form'  %>
  </div>

  <div id="map" >
  </div>

<script type="text/jscript">
var wor = 0

const selectWords = async data => {
  $.ajax({
    type: 'POST',
    url: '/pages/words_search',
    data: data,
    success: function(data) {
      wor = data
    },
    error: function(data) {
      console.log('error')
    }
  })
}


console.log(wor)

var map = L.map('map').setView([48.575, 35.508], 6);

L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
    maxZoom: 18,
    attribution: 'MapController data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
    '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
    'Imagery © <a href="http://mapbox.com">Mapbox</a>',
    id: 'mapbox.streets'
}).addTo(map);

//  var css = ['A', 'B', 'C', 'D', 'E'];
//    var dial = wor;
//    console.log(`wor is ${dial}`)
//        dial.forEach(function (dic, index, dial) {
//
//
//    var markers = L.markerClusterGroup({
//        maxClusterRadius: 120,
//        iconCreateFunction: function (cluster) {
//            let markers = cluster.getAllChildMarkers();
//            let n = 0;
//            for (let i = 0; i < markers.length; i++) {
//                n += 1
//            }
//
//            let c = css[index-1];
//            return new L.DivIcon({ html: '<div><span>' + n + '</span></div>', className: 'marker-cluster marker-cluster-' + c, iconSize: new L.Point(40, 40) });
//        },
//        //Disable all of the defaults:
//        spiderfyOnMaxZoom: false, showCoverageOnHover: false, zoomToBoundsOnClick: true
//    });
//     index++;
// console.log(index);
//
//     var words = wor;
//
//
//
//     words.forEach(function (word, i, words) {
//         if(word.dialect_words == dic) {
//             let title = word.dialect_words;
//
//             let marker = L.marker(L.latLng(word.X, word.Y), {title: title});
//             marker.bindPopup(title);
//             markers.addLayer(marker);
//         }
//     });
//
//     map.addLayer(markers);
//    })

</script>

app/views/pages/search.html.erb
Users<br/>
<% if @users.present? %>
  <% @users.each do |user|  %>
    <%= user.email %>
    <%= user.name %>
    <%= user.surname %><br/>
  <% end %>
<% end %>
Posts<br/>
<% if @posts.present? %>
  <% @posts.each do |post| %>
    <%= image_tag post.mainphoto.url %>
    <%= post.article %><br/>
  <% end %>
<% end %>
Words<br/>
<% if @words.present? %>
  <% @words.each do |word| %>
    <%= word.official_word %>
    <%= word.dialect_word %>
    <%= word.city.city %>
  <% end %>
<% end %>